# System constants used across BBE

# General
NUM_OF_COMPETITORS = 2
NUM_OF_EXCHANGES = 4
PRE_RACE_BETTING_PERIOD_LENGTH = 10

# Data Store Attributes
RACE_DATA_FILENAME = 'race_event_core.csv'

# Message Protocol Numbers
EXCHANGE_UPDATE_MSG_NUM = 1
RACE_UPDATE_MSG_NUM = 2

# Exchange Attributes
MIN_ODDS = 1.00
MAX_ODDS = 1000.00

# Print-Outs
TBBE_VERBOSE = False
SIM_VERBOSE = True
EXCHANGE_VERBOSE = False

# Event Attributes
MIN_RACE_LENGTH = 1000
MAX_RACE_LENGTH = 3200

MIN_RACE_UNDULATION = 0
MAX_RACE_UNDULATION = 100

MIN_RACE_TEMPERATURE = 0
MAX_RACE_TEMPERATUE = 50
