# System constants used across BBE

# Print-Outs
SIM_VERBOSE = True

# Event Attributes
MIN_RACE_LENGTH = 1000
MAX_RACE_LENGTH = 3200

MIN_RACE_UNDULATION = 0
MAX_RACE_UNDULATION = 100

MIN_RACE_TEMPERATURE = 0
MAX_RACE_TEMPERATUE = 50
